modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"

[[mods]]
modId = "legendcontrol_defender"
version = "${project_version}"
displayName = "${project_name}-Defender"
logoFile = "logo.png"
authors = "Vecoo"
description = "Sidemod for Pixelmon. It is a module of the main LegendControl for the protection of legends."

[[dependencies.legendcontrol_defender]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol_defender]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol_defender]]
modId = "pixelmon"
type = "required"
versionRange = "[9.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.legendcontrol_defender]]
modId = "extralib"
type = "required"
versionRange = "[1.6,)"
ordering = "NONE"
side = "SERVER"