modLoader="javafml"
loaderVersion="[48,)"
license="All Rights Reserved"

[[mods]]
modId="legendcontrol"
version="2.2.1"
displayName="LegendControl"
logoFile ="logo.png"
authors="Vecoo"
description="Sidemode for Pixelmon. Changing the spawn elements of legendary Pokémon."

[[dependencies.legendcontrol]]
modId="forge"
mandatory=true
versionRange="[48.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.legendcontrol]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.legendcontrol]]
modId="pixelmon"
mandatory=true
versionRange="[9.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.legendcontrol]]
modId="extralib"
mandatory=true
versionRange="[1.2,)"
ordering="AFTER"
side="BOTH"