modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "legendcontrol"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Sidemod for Pixelmon. Changing the spawn elements of legendary pokemon."

[[dependencies.legendcontrol]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "pixelmon"
mandatory = true
versionRange = "[9.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "extralib"
mandatory = true
versionRange = "[1.8,)"
ordering = "NONE"
side = "BOTH"