modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="legendcontrol"
version="1.1.0"
displayName="LegendControl"
logoFile ="logo.png"
authors="Vecoo"
description="Sidemod for Pixelmon. Changed spawn system for legendary Pokemon."

[[dependencies.legendcontrol]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.legendcontrol]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="BOTH"

[[dependencies.legendcontrol]]
modId="pixelmon"
mandatory=true
versionRange="[9.1,)"
ordering="NONE"
side="BOTH"