modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"

[[mods]]
modId = "legendcontrol"
version = "3.0.1"
displayName = "LegendControl"
logoFile = "logo.png"
authors = "Vecoo"
description = "Sidemod for Pixelmon. Changing the spawn elements of legendary pokemon."

[[dependencies.legendcontrol]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "pixelmon"
mandatory = true
versionRange = "[9.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "extralib"
mandatory = true
versionRange = "[1.5,)"
ordering = "NONE"
side = "SERVER"